const DAY_MS = 24 * 60 * 60 * 1000
const unsubscribedState = {subscribed: false}

export function createMockFixture(referenceDate = new Date()) {
	const today = atHour(referenceDate, 10)
	const laterToday = new Date(today.getTime() + 2 * 60 * 60 * 1000)
	const tomorrow = new Date(today.getTime() + DAY_MS)
	const nextWeek = new Date(today.getTime() + 6 * DAY_MS)
	const yesterday = new Date(today.getTime() - DAY_MS)

	return {
		user: {
			id: 1,
			name: 'Smoke User',
			username: 'smoke-user',
			email: 'smoke@example.test',
			settings: {
				default_project_id: 1,
				timezone: 'Europe/Amsterdam',
				avatar_provider: 'default',
				email_reminders_enabled: false,
				overdue_tasks_reminders_enabled: false,
				overdue_tasks_reminders_time: '07:00',
			},
		},
		users: [
			{
				id: 1,
				name: 'Smoke User',
				username: 'smoke-user',
				email: 'smoke@example.test',
			},
			{
				id: 2,
				name: 'Alex Partner',
				username: 'apartner',
				email: 'alex@example.test',
			},
			{
				id: 3,
				name: 'Jamie Rivers',
				username: 'jamie',
				email: 'jamie@example.test',
			},
		],
		teams: [
			{
				id: 1,
				name: 'Home Team',
				description: 'Shared household team',
				is_public: false,
				members: [
					{
						id: 1,
						name: 'Smoke User',
						username: 'smoke-user',
						email: 'smoke@example.test',
						admin: true,
					},
				],
			},
		],
		projectUserShares: [],
		projectTeamShares: [],
		linkShares: [],
		labels: [
			{id: 1, title: 'Urgent', hex_color: '#1973ff'},
			{id: 2, title: 'Personal', hex_color: '#6aa84f'},
		],
		sessions: [
			{
				id: 'session-1',
				device_info: 'Smoke Browser',
				ip_address: '127.0.0.1',
				last_active: today.toISOString(),
				created: today.toISOString(),
			},
			{
				id: 'session-2',
				device_info: 'Phone',
				ip_address: '127.0.0.2',
				last_active: laterToday.toISOString(),
				created: today.toISOString(),
			},
		],
		notifications: [
			{
				id: 1,
				name: 'task.comment',
				read: false,
				read_at: null,
				created: laterToday.toISOString(),
				notification: {
					doer: {
						id: 2,
						name: 'Alex Partner',
						username: 'apartner',
						email: 'alex@example.test',
					},
					task: {
						id: 201,
						title: 'Smoke suite rollout',
						project_id: 2,
					},
					project: {
						id: 2,
						title: 'Work',
					},
					comment: {
						id: 1,
						comment: 'Proxy route is ready for smoke verification.',
					},
				},
			},
			{
				id: 2,
				name: 'task.reminder',
				read: false,
				read_at: null,
				created: today.toISOString(),
				notification: {
					task: {
						id: 101,
						title: 'Buy milk',
						project_id: 1,
					},
					project: {
						id: 1,
						title: 'Inbox',
					},
				},
			},
			{
				id: 3,
				name: 'project.created',
				read: false,
				read_at: null,
				created: yesterday.toISOString(),
				notification: {
					doer: {
						id: 3,
						name: 'Jamie Rivers',
						username: 'jamie',
						email: 'jamie@example.test',
					},
					project: {
						id: 3,
						title: 'Travel',
					},
				},
			},
			{
				id: 4,
				name: 'task.comment',
				read: false,
				read_at: null,
				created: laterToday.toISOString(),
				notification: {
					doer: {
						id: 1,
						name: 'Smoke User',
						username: 'smoke-user',
						email: 'smoke@example.test',
					},
					task: {
						id: 102,
						title: 'Prepare daily summary',
						project_id: 1,
					},
					project: {
						id: 1,
						title: 'Inbox',
					},
					comment: {
						id: 2,
						comment: 'I already handled this one.',
					},
				},
			},
		],
		savedFilters: [
			{
				id: 0,
				projectId: -1,
				title: 'Focused Work',
				description: 'Saved filter pseudo-project',
				is_favorite: false,
				created: today.toISOString(),
				updated: laterToday.toISOString(),
				filters: {
					filter: 'label = "Urgent" && done = false',
					filter_include_nulls: false,
					sort_by: ['position', 'id'],
					order_by: ['asc', 'asc'],
				},
			},
		],
		projects: [
			{
				id: 1,
				title: 'Inbox',
				description: 'Default capture project',
				parent_project_id: 0,
				position: 100,
				identifier: 'INBOX',
				is_favorite: true,
				is_archived: false,
			},
			{
				id: 2,
				title: 'Work',
				description: 'Main work project',
				parent_project_id: 0,
				position: 200,
				identifier: 'WORK',
				is_favorite: false,
				is_archived: false,
				subscription: {...unsubscribedState},
			},
			{
				id: 3,
				title: 'Travel',
				description: 'Upcoming vacation planning',
				parent_project_id: 2,
				position: 300,
				identifier: 'TRAVEL',
				is_favorite: false,
				is_archived: false,
			},
			{
				id: -1,
				title: 'Focused Work',
				description: 'Saved filter pseudo-project',
				parent_project_id: 0,
				position: 400,
				identifier: 'FILTER',
				is_favorite: false,
				is_archived: false,
			},
		],
		viewsByProjectId: {
			1: [{id: 11, project_id: 1, title: 'List', view_kind: 'list'}],
			2: [
				{id: 12, project_id: 2, title: 'List', view_kind: 'list'},
				{id: 16, project_id: 2, title: 'Alt List', view_kind: 'list'},
				{id: 15, project_id: 2, title: 'Board', view_kind: 'kanban', default_bucket_id: 151, done_bucket_id: 152},
			],
			3: [{id: 13, project_id: 3, title: 'List', view_kind: 'list'}],
			'-1': [{id: 14, project_id: -1, title: 'List', view_kind: 'list'}],
		},
		bucketsByViewId: {
			15: [
				{
					id: 151,
					project_id: 2,
					project_view_id: 15,
					title: 'To Do',
					position: 100,
					limit: 0,
					tasks: [],
				},
				{
					id: 152,
					project_id: 2,
					project_view_id: 15,
					title: 'Done',
					position: 200,
					limit: 0,
					tasks: [],
				},
			],
		},
		tasks: [
			{
				id: 101,
				project_id: 1,
				title: 'Buy milk',
				description: 'Pick up groceries on the way home',
				done: false,
				is_favorite: false,
				due_date: laterToday.toISOString(),
				position: 100,
				priority: 2,
				percent_done: 15,
				created: yesterday.toISOString(),
				updated: today.toISOString(),
				done_at: null,
				read: false,
				read_at: null,
				subscription: {...unsubscribedState},
				labelIds: [2],
				parentTaskId: null,
			},
			{
				id: 102,
				project_id: 1,
				title: 'Prepare daily summary',
				description: 'Write the quick stand-up notes',
				done: false,
				is_favorite: false,
				due_date: today.toISOString(),
				position: 200,
				priority: 1,
				percent_done: 35,
				created: yesterday.toISOString(),
				updated: laterToday.toISOString(),
				done_at: null,
				read: false,
				read_at: null,
				subscription: {...unsubscribedState},
				labelIds: [1],
				parentTaskId: null,
			},
			{
				id: 103,
				project_id: 1,
				title: 'Archive receipts',
				description: 'File the completed paper receipts',
				done: true,
				is_favorite: false,
				due_date: null,
				position: 300,
				priority: 0,
				percent_done: 100,
				created: yesterday.toISOString(),
				updated: today.toISOString(),
				done_at: today.toISOString(),
				labelIds: [],
				parentTaskId: null,
			},
			{
				id: 201,
				project_id: 2,
				title: 'Smoke suite rollout',
				description: 'CI and lint coverage for the PWA',
				done: false,
				is_favorite: false,
				due_date: tomorrow.toISOString(),
				position: 100,
				priority: 5,
				percent_done: 65,
				repeat_after: 604800,
				repeat_from_current_date: false,
				assignees: [
					{
						id: 2,
						name: 'Alex Partner',
						username: 'apartner',
						email: 'alex@example.test',
					},
				],
				comments: [
					{
						id: 1,
						comment: 'Proxy route is ready for smoke verification.',
						author: {
							id: 1,
							name: 'Smoke User',
							username: 'smoke-user',
							email: 'smoke@example.test',
						},
						created: yesterday.toISOString(),
						updated: today.toISOString(),
					},
				],
				attachments: [
					{
						id: 1,
						task_id: 201,
						created_by: {
							id: 1,
							name: 'Smoke User',
							username: 'smoke-user',
							email: 'smoke@example.test',
						},
						file: {
							id: 1,
							name: 'rollout-checklist.png',
							mime: 'image/png',
							size: 18432,
						},
						created: today.toISOString(),
					},
				],
				reminders: [
					{
						reminder: new Date(tomorrow.getTime() - 60 * 60 * 1000).toISOString(),
						relative_period: -3600,
						relative_to: 'due_date',
					},
				],
				created: yesterday.toISOString(),
				updated: laterToday.toISOString(),
				done_at: null,
				read: false,
				read_at: null,
				subscription: {subscribed: true},
				labelIds: [1],
				parentTaskId: null,
			},
			{
				id: 202,
				project_id: 2,
				title: 'Backend proxy coverage',
				description: 'Exercise the main Node BFF routes',
				done: false,
				is_favorite: false,
				due_date: tomorrow.toISOString(),
				position: 200,
				priority: 3,
				percent_done: 0,
				created: yesterday.toISOString(),
				updated: today.toISOString(),
				done_at: null,
				labelIds: [],
				parentTaskId: null,
			},
			{
				id: 203,
				project_id: 2,
				title: 'Release checklist',
				description: 'Parent task for nested smoke items',
				done: false,
				is_favorite: false,
				due_date: nextWeek.toISOString(),
				position: 300,
				priority: 4,
				percent_done: 20,
				created: yesterday.toISOString(),
				updated: laterToday.toISOString(),
				done_at: null,
				labelIds: [],
				parentTaskId: null,
			},
			{
				id: 204,
				project_id: 2,
				title: 'Verify nested task rendering',
				description: 'Child task for project task tree coverage',
				done: false,
				is_favorite: false,
				due_date: nextWeek.toISOString(),
				position: 100,
				priority: 2,
				percent_done: 50,
				created: yesterday.toISOString(),
				updated: laterToday.toISOString(),
				done_at: null,
				labelIds: [],
				parentTaskId: 203,
			},
			{
				id: 301,
				project_id: 3,
				title: 'Book flights',
				description: 'Travel planning and reservations',
				done: false,
				is_favorite: false,
				due_date: nextWeek.toISOString(),
				position: 100,
				priority: 2,
				percent_done: 10,
				created: yesterday.toISOString(),
				updated: today.toISOString(),
				done_at: null,
				labelIds: [2],
				parentTaskId: null,
			},
		],
	}
}

export function cloneFixture(fixture) {
	return structuredClone(fixture)
}

function atHour(value, hour) {
	const date = new Date(value)
	date.setHours(hour, 0, 0, 0)
	return date
}
